### ISSUE TITLE
What is the name of the actual telegram Bot?

### ISSUE THREAD

**Issue by gkartalis** [similicious/berlin-buergeramt-bot#1]
Thanks for making this! Would love to try it out! 

One question only, what is the telegram handle of the bot in order to be able to find it in telegram and try it out?

Thanks for having this open source! 🔥

**Comment by similicious** [comment]
Hey @gkartalis!

Thanks for the feedback. As of now, the bot is meant to be self hosted. So just grab a raspberry pi or a cheap vps and run it there. You'll need to create a bot yourself (see the telegram docs, it's easy!)

Now that I'm thinking of it, it could be nice to just message the bot an appointment page and get notified that way. But then my bot could generate a lot of traffic and might be rate limited or something.

Anyway, reach out if you need help settting up the bot :)

**Comment by gkartalis** [comment]
Amazing! Thanks a lot! 

Will give it a try to set it up in the following weeks and will let you know if I encounter any issue! 🔥
