### ISSUE TITLE
BOOKING_URL from env

### ISSUE THREAD

**Issue by siasalar** [similicious/berlin-buergeramt-bot#2]
The BOOKING_URL message is not clear in readme file, I have tried different URLs, and was not successful, for some of them there is no cookies in response, for some of them it will receive 302 status code(redirected).
Can you please update it with the real example?

**Comment by similicious** [comment]
Hey siaslara,

a valid `BOOKING_URL` looks like this `https://service.berlin.de/terminvereinbarung/termin/tag.php?termin=1&dienstleister=327294&anliegen[]=120686&herkunft=1` . When accessed, the server will set a cookie and redirect to the appointment select page. I just tested, that  the bot still works.

To get the `BOOKING_URL` use the link behind these links / buttons:
![grafik](https://user-images.githubusercontent.com/33279934/175475043-f415f704-8d3f-48aa-bc89-1c53eb187543.png)

![grafik](https://user-images.githubusercontent.com/33279934/175474975-48f3f574-e1cc-41d9-a58a-51c72b7f5a13.png)

**Comment by siasalar** [comment]
Thanks for the reply, I couldn't find where could you find the shared photos, in which link I mean.
