### ISSUE TITLE
redirect

### ISSUE THREAD

**Issue by siasalar** [similicious/berlin-buergeramt-bot#3]
https://github.com/similicious/berlin-buergeramt-bot/blob/c30a8ef9bddc25b05b3c2e5c2333321d59cebbdd/get-booking-page-html.js#L8

As we already talked about the BOOKING_URL:
> BOOKING_URL looks like this https://service.berlin.de/terminvereinbarung/termin/tag.php?termin=1&dienstleister=327294&anliegen[]=120686&herkunft=1 . When accessed, the server will set a cookie and redirect to the appointment select page

The question is how and why we you set `followRedirect: false` although we know that this server set a cookie and then redirect...

**Comment by similicious** [comment]
If I recall correctly, the cookies were not sent back after redirect by the http client. Might work now 🤷

**Comment by similicious** [comment]
Jup, I'm getting a `MaxRedirectsError`: `Redirected 10 times. Aborting`.

I'll try with undici.

**Comment by similicious** [comment]
Undici won't flollow the redirect at all. So I think that code has it's place.
I added a comment though, cheers.

closed in 4e6f0d384c25a941605ffd9c1ccac27fbc9ac37f

**Comment by siasalar** [comment]
Also I think in your code, you are not checking the next months calendar:
`nachster Monath...`
<img width="663" alt="image" src="https://user-images.githubusercontent.com/51620597/175647549-44b9337a-b580-4a39-923d-f3ffaa24828f.png">

**Comment by similicious** [comment]
This is intended. I added a section in the README.

see 24ce7aa4a8ef7c38debbe9dea846db38003012aa
