### ISSUE TITLE
"Termin" URL is always the same - tool still working?

### ISSUE THREAD

**Issue by smartini87** [similicious/berlin-buergeramt-bot#4]
When setting up the environment file (.env) I noticed that all link behind "Termin buchen" are always the same.
--> https://service.berlin.de/terminvereinbarung/termin/day/
BOOKING_URL=The link to the appointments page. Use the link behind "Termin buchen" or "Termin berlinweit suchen" buttons.
The url makes no sense, because it seems the real data will be loaded elsewise while clicking on it.

So I wonder whether the tool is still working and or did the website logic change?

Here are clearly slots available, but the link above
![grafik](https://user-images.githubusercontent.com/44892609/199143087-2b527b97-785f-4369-9c01-7ab651878cd4.png)

But the result is the following:
![grafik](https://user-images.githubusercontent.com/44892609/199143238-2af61291-d8b3-4374-add3-5efe310b804d.png)

**Comment by similicious** [comment]
Try right clicking the "Termin buchen" or "Termin berlinweit suchen" button to copy the url. The url contains the type of appointment and the location. A valid link looks like this:
```
https://service.berlin.de/terminvereinbarung/termin/tag.php?termin=1&dienstleister=327334&anliegen[]=120703&herkunft=1
```

**Comment by smartini87** [comment]
Thanks, I tried it already.

For test purposes I tried to get appointments where there are usually slots open.
I get the links from this category: https://service.berlin.de/dienstleistung/121921/#wohin

https://service.berlin.de/terminvereinbarung/termin/tag.php?termin=1&dienstleister=122058&anliegen[]=121921&herkunft=1
https://service.berlin.de/terminvereinbarung/termin/tag.php?termin=1&dienstleister=324673&anliegen[]=121921&herkunft=1

Both have several free slots, but I receive the following error:
![grafik](https://user-images.githubusercontent.com/44892609/199204326-0ad026de-05e5-4b2d-9a98-87ae57d4ee63.png)

![grafik](https://user-images.githubusercontent.com/44892609/199204343-6ffe1c8b-171f-4fcc-b355-b70bf27cdc47.png)


When I try to get an appointment for my real purpose in this category:
https://service.berlin.de/dienstleistung/318998/

I fetch the following link:
https://service.berlin.de/terminvereinbarung/termin/tag.php?termin=1&dienstleister=327427&anliegen[]=318998&herkunft=1

This is the result:
![grafik](https://user-images.githubusercontent.com/44892609/199204540-d1c4cae4-a857-4ff2-94ce-a9ac073d8f84.png)

But I don't know whether the result is valid or not, because there's no slot free as of now.

This is my -env settings:
![grafik](https://user-images.githubusercontent.com/44892609/199204653-e1bc2b7f-3394-4e0f-ae64-f5308e941a8b.png)

**Comment by similicious** [comment]
I just tried out your .env and could reproduce the error.

The 404 HTTPError is thrown, when the script tries to reach out to Telegrams API to send a message. As you have no bot token or chatId set, the assembled URL is not correct.

I'm gonna improve the script a bit, to make the error more clear.

**Comment by smartini87** [comment]
Thank you for that hint. That did the trick.
I filled the missing input to the .env file, my bot is now repsonding to me.

Yes, a adjustment of the error message would be helpful for others I think.

**Comment by similicious** [comment]
Adressed this issue in https://github.com/similicious/berlin-buergeramt-bot/commit/37b1b9d432f8093f87d37ca463b7b61d34cf6464
