### ISSUE TITLE
Connot find module 'dotenv'

### ISSUE THREAD

**Issue by MrAdam420** [similicious/berlin-buergeramt-bot#7]
`pi@raspberrypi:~/berlin-buergeramt-bot $ node src/index.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'dotenv'
Require stack:
- /home/pi/berlin-buergeramt-bot/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/berlin-buergeramt-bot/src/index.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/pi/berlin-buergeramt-bot/src/index.js' ]
}
`

**Comment by MrAdam420** [comment]
Fixed by adding `npm install dotenv --save`

**Comment by similicious** [comment]
Did you run npm install?

Seems like dependencies are not installed.

**Comment by MrAdam420** [comment]
Yes I did, but the dotenv dependency was missing.

**Comment by MrAdam420** [comment]
I finally get an output, but its an error haha. 

`node src/index.js
2023-03-18T14:30:17.860Z 0 appointments found.
HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/home/pi/berlin-buergeramt-bot/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1679149817877,
    socket: 1679149817880,
    lookup: 1679149817912,
    connect: 1679149817940,
    secureConnect: 1679149818011,
    upload: 1679149818012,
    response: 1679149818045,
    end: 1679149818047,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 3,
      dns: 32,
      tcp: 28,
      tls: 71,
      request: 1,
      firstByte: 33,
      download: 2,
      total: 170
    }
  }
}
`

**Comment by similicious** [comment]
Looks like telegram is not configured properly.

**Comment by MrAdam420** [comment]
It sends the whole Error message every Interval to my telegram bot.

**Comment by MrAdam420** [comment]
Do I need to add Quotation marks to my strings like the link and email?

Here is my Telegram output:
Berlin Buergeramt Bot has started.
{"name":"HTTPError","code":"ERR_NON_2XX_3XX_RESPONSE","timings":{"start":1679150502814,"socket":1679150502816,"lookup":1679150502843,"connect":1679150502871,"secureConnect":1679150502915,"upload":1679150502915,"response":1679150502959,"end":1679150502961,"phases":{"wait":2,"dns":27,"tcp":28,"tls":44,"request":0,"firstByte":44,"download":2,"total":147}}}

**Comment by similicious** [comment]
You don't need quotes at all in .env

**Comment by MrAdam420** [comment]
Then I dont know what could be wrong. 

BOOKING_URL='https://service.berlin.de/terminvereinbarung/termin/tag.php?termin=1&dienstleister=122309&anliegen[]=121151&herkunft=1'
USER_AGENT='email'
CHECK_INTERVAL_MINUTES=3
HEALTHCHECKS_IO_TOKEN=1
TELEGRAM_BOT_TOKEN='botToken:Token'
TELEGRAM_CHAT_ID='myChatid'

Do I use the wrong link?

**Comment by similicious** [comment]
Maybe the bot token is in the wrong format. You need just the token, omitting the bot prefix.

**Comment by similicious** [comment]
Link is correct

**Comment by MrAdam420** [comment]
I think the Token is correct, otherwise I would not recieve the Telegram Messages.
